name: End-to-end tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install firebase-tools

      - name: Authenticate with Firebase
        run: firebase use default 

      - name: Deploy to Firebase
        run: npm run deploy:h


      - name: Cypress run
        uses: cypress-io/github-action@v6
