name: Pull Request Validation

on:
    pull_request:
        branches:
            - dev
            - main

jobs:
    basic-checks:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [16.x]
  
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: "npm"
            
        - name: Execute Unit tests
          run: |
            npm ci
            npm run test:unit

        - name: Run ESLint
          run: npm run lint

        - name: Run TypeScript type checking
          run: npm run typecheck

        # - name: Cypress run
        #   uses: cypress-io/github-action@v6

        # - name: Vitest
        #   run: npm run test:unit
